"""empty message

Revision ID: 060967c8ec4f
Revises: 8e0574e2fc49
Create Date: 2018-01-27 21:59:46.213600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060967c8ec4f'
down_revision = '8e0574e2fc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkbook_amount'), 'checkbook', ['amount'], unique=True)
    op.create_index(op.f('ix_checkbook_description'), 'checkbook', ['description'], unique=True)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.drop_index(op.f('ix_checkbook_description'), table_name='checkbook')
    op.drop_index(op.f('ix_checkbook_amount'), table_name='checkbook')
    op.drop_table('checkbook')
    # ### end Alembic commands ###
