"""empty message

Revision ID: 30b51731a791
Revises: 
Create Date: 2018-01-29 15:38:29.976371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b51731a791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('cleared', sa.Boolean(), nullable=True),
    sa.Column('cleared_date', sa.String(length=30), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkbook')
    # ### end Alembic commands ###
